name: Solar Dash
url: http://dash.jimhowk.com
description: My Solarized Digital Notes

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge
markdown: kramdown

gems: [jekyll-paginate]

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
